services:
  backend:
    build: ./
    environment:
      - PORT=4000
      - DEBUG=False
      - ALLOWED_HOSTS=0.0.0.0
      - ALLOWED_ORIGINS=*
      - SERVER_TIMEZONE=Asia/Kolkata
      - DATABASE_URI=mongodb://mongodb:27017
      - DATABASE_NAME=database
      - JWT_SECRET=47tc47bc4t46rt4365346r
      - JWT_EXPIRY_HOURS=14
    ports:
      - "4000:4000"
        
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data: