apiVersion: 1

datasources:
  - name: prometheus
    uid: bfet27idk2br4e
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      pdcInjected: false