{
 "title": "Http Requests",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(go_info, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Http Request Rate",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(job)(rate(http_requests_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} (avg)"
    }
   ]
  },
  {
   "title": "Http Request Error Rate",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(job)(rate(http_request_errors_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} (avg)"
    }
   ]
  },
  {
   "title": "Http RequesAverage Duration",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job)(rate(http_request_duration_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}} (avg)"
    }
   ]
  }
 ]
}